export const ADD_TODO_REQUESTED = 'ADD_TODO_REQUESTED';
export const ADD_TODO_SUCCEEDED = 'ADD_TODO_SUCCEEDED';
export const ADD_TODO_FAILED = 'ADD_TODO_FAILED';

export const EDIT_TODO_REQUESTED = 'EDIT_TODO_REQUESTED';
export const EDIT_TODO_SUCCEEDED = 'EDIT_TODO_SUCCEEDED';
export const EDIT_TODO_FAILED = 'EDIT_TODO_FAILED';

export const DELETE_TODO_REQUESTED = 'DELETE_TODO_REQUESTED';
export const DELETE_TODO_SUCCEEDED = 'DELETE_TODO_SUCCEEDED';
export const DELETE_TODO_FAILED = 'DELETE_TODO_FAILED';

export const FETCH_TODOS_REQUESTED = 'FETCH_TODOS_REQUESTED';
export const FETCH_TODOS_SUCCEEDED = 'FETCH_TODOS_SUCCEEDED';
export const FETCH_TODOS_FAILED = 'FETCH_TODOS_FAILED';
